unit uAcessToken;

//  *************************************************
//    Generated By: JsonToDelphiClass - 0.65
//    Project link: https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
//    Generated On: 2020-06-24 14:30:12
//  *************************************************
//    Created By  : Petar Georgiev - 2014
//    WebSite     : http://pgeorgiev.com
//  *************************************************

interface

uses Generics.Collections, Rest.Json;

type
  TAcessToken = class
  private
    FAccess_token: String;
    FExpires_in: Extended;
    FRefresh_token: String;
    FToken_type: String;
    Femail_password: string;
    Fid: Integer;
  public
    property access_token: String read FAccess_token write FAccess_token;
    property expires_in: Extended read FExpires_in write FExpires_in;
    property refresh_token: String read FRefresh_token write FRefresh_token;
    property token_type: String read FToken_type write FToken_type;
    property email_password: string read Femail_password write Femail_password;
    property id: Integer read Fid write Fid;
    function ToJsonString: string;
    class function FromJsonString(AJsonString: string): TAcessToken;
  end;

implementation

{TAcessToken}

function TAcessToken.ToJsonString: string;
begin
  Result := TJson.ObjectToJsonString(Self);
end;

class function TAcessToken.FromJsonString(AJsonString: string): TAcessToken;
begin
  Result := TJson.JsonToObject<TAcessToken>(AJsonString);
end;

end.

